# fly.toml app configuration file generated for bmm-bot-2 on 2025-05-21T22:09:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bmm-bot-2"
primary_region = "fra"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # ← disable auto stop
  auto_start_machines = true
  min_machines_running = 1    # ← keep at least 1 machine running
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
# fly.toml app configuration file generated for bmm-bot-2 on 2025-05-21T22:09:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bmm-bot-2"
primary_region = "fra"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # ← disable auto stop
  auto_start_machines = true
  min_machines_running = 1    # ← keep at least 1 machine running
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

